### ISSUE TITLE
Add a flag that allows things in /etc/ directory to NOT be treated as conffiles

### ISSUE THREAD

**Issue by bill-freeman** [xolox/python-deb-pkg-tools#19]
currently everything in /etc/ directory gets treated as conffiles.  There are siuations where you dont want this to happen.  You should update the function "update_conffiles(directory) in the package.py to accept a boolean that defines if /etc/ is treated as conffiles or not.  You should also make it default to yes for legacy support.

**Comment by xolox** [comment]
Hi and thanks for the feedback. I've just released [deb-pkg-tools 7.0](https://deb-pkg-tools.readthedocs.io/en/latest/changelog.html#release-7-0-2020-02-07) which adds support for `build_package(update_conffiles=False)` as [documented here](https://deb-pkg-tools.readthedocs.io/en/latest/api.html#deb_pkg_tools.package.build_package).
